# hdmi drivers

obj-$(CONFIG_JZ4760_HDMI_DISPLAY)                             += it66121FN/

#obj-$(CONFIG_JZ4760_HDMI_DISPLAY)                             += it6610/
#obj-$(CONFIG_JZ4760_HDMI_DISPLAY)                              += ep932/
