
obj-$(CONFIG_ISP)		+= camera_source/isp/
obj-$(CONFIG_OV2640)		+= camera_source/ov2640/
obj-$(CONFIG_OV9650)		+= camera_source/ov9650/

obj-$(CONFIG_JZ_CIM)		+= jz_cim_core.o jz_sensor.o  jz_cim_board_lynx.o

obj-$(CONFIG_JZ4750_APUS)	+= jz_cim_board_apus.o
obj-$(CONFIG_JZ4750_AQUILA)	+= jz_cim_board_aquila.o
obj-$(CONFIG_JZ4760_ALTAIR)	+= jz_cim_board_altair.o
obj-$(CONFIG_JZ4760B_ALTAIR)	+= jz_cim_board_altair.o
obj-$(CONFIG_JZ4760_PT701)	+= jz_cim_board_pt701.o
obj-$(CONFIG_JZ4760_PT701I)	+= jz_cim_board_pt701.o
obj-$(CONFIG_JZ4760_TABLET_8II)	+= jz_cim_board_tablet_8ii.o
obj-$(CONFIG_JZ4760_TABLET_8II_MOVINAND) += jz_cim_board_tablet_8ii.o
obj-$(CONFIG_JZ4760B_TABLET_8II_MOVINAND) 	+= jz_cim_board_tablet_8ii.o
obj-$(CONFIG_JZ4760_Z800)     += jz_cim_board_z800.o
obj-$(CONFIG_JZ4760_LYNX)	+= jz_cim_board_lynx.o
obj-$(CONFIG_JZ4760B_LYNX)	+= jz_cim_board_lynx.o
obj-$(CONFIG_JZ4770_MAPLE)	+= jz_cim_board_maple.o

obj-$(CONFIG_OV7690)		+= camera_source/ov7690/
obj-$(CONFIG_OV3640)		+= camera_source/ov3640/
obj-$(CONFIG_OV2655)		+= camera_source/ov2655/
obj-$(CONFIG_CM3511)		+= camera_source/cm3511/
obj-$(CONFIG_HI253)			+= camera_source/hi253/
obj-$(CONFIG_BF3703)		+= camera_source/bf3703/
obj-$(CONFIG_JZ_FAKE_SENSOR)	+= camera_source/fake/


obj-$(CONFIG_GC0308)	+= camera_source/gc0308/
obj-$(CONFIG_GC0309)		+= camera_source/gc0309/
obj-$(CONFIG_GC0328)		+= camera_source/gc0328/
obj-$(CONFIG_GC2015)	+= camera_source/gc2015/
obj-$(CONFIG_MY704)		+= camera_source/my704/
obj-$(CONFIG_HI704)		+= camera_source/hi704/
obj-$(CONFIG_OV2655_Z800)	+= camera_source/ov2655_z800/
obj-$(CONFIG_OV7675)            += camera_source/ov7675/
obj-$(CONFIG_CM3511_Z800)	+= camera_source/cm3511_z800/
obj-$(CONFIG_F2655)		+= camera_source/f2655/
obj-$(CONFIG_SIV120B)		+= camera_source/siv120b/
