# hdmi it6610 drivers
#obj-$(CONFIG_HDMI_IT6610)                             +=it6610_i2c.o  it6610_drv.o  chip_drv.o chip_sys.o i2c_fun.o
#obj-$(CONFIG_JZ4760_HDMI_DISPLAY)                    +=it6610_drv.o  chip_drv.o chip_sys.o gpio_i2c.o
obj-$(CONFIG_JZ4760_HDMI_DISPLAY)                    +=main_proc.o  gpio_i2c.o hdmitx_drv.o hdmitx_sys.o hdmitx_hdcp.o hdmitx_input.o sha1.o csc.o